[build]
builder = "nixpacks"
buildCommand = "cd server && npm install && npx prisma generate"

[deploy]
startCommand = "cd server && npx prisma migrate deploy && node index.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
